version: '3.8'

services:
  my_service:
    image: ubuntu-full-packages:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - my_data_volume:/app/data
      - type: bind
        source: ./local_data
        target: /app/data_local

    networks:
      - my_network

volumes:
  my_data_volume:
    driver: local

networks:
  my_network:
    driver: bridge
